config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'notifications#index'

  resources :notifications, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #comfirmable

  after_commit :send_welcome_notification, on: :create

  validates :first_name, :last_name, :phone_number, :email, presence: true
  validates :email, uniqueness: true
  has_many :messages
  
  private

  def send_welcome_notification
    SmsService.send_welcome_sms(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number, :first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :first_name, :last_name])
    end
  end
  

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @messages = current_user.messages.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SMS Notification</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">SMS App</a> <!-- Replace # with the root path if necessary -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <!-- Notifications Link -->
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Notifications', notifications_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <span class="navbar-text mr-3">Welcome, <%= current_user.first_name %></span>
            </li>
            <li class="nav-item">
              <%= form_with url: destroy_user_session_path, method: :delete do %>
                <%= button_tag(type: 'submit', class: 'btn btn-link nav-link') do %>
                  Logout
                <% end %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-3">
    <%= yield %>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/notifications/index.html.erb
<h1 class="mb-4">Twilio SMS Notifications</h1>

<div class="container">
  <div class="row">
    <div class="col-12">
      <ul class="list-group">
        <% @messages.each do |message| %>
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold">To: <%= message.to %></div>
              Body: <%= message.body %>
              <% if message.status == 'failed' %>
                <div class="text-danger">Error: <%= message.error_message %></div>
              <% else %>
                <div class="text-success">Status: <%= message.status %></div>
              <% end %>
            </div>
            <span class="badge bg-primary rounded-pill">
              Sent at: <%= message.created_at.strftime('%Y-%m-%d %H:%M:%S %Z') %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>